language: java
jdk:
- oraclejdk8
deploy:
  provider: releases
  user: Kristjanjoelk
  password: 
    secure: FjIEMEF/TF9AOMO4ni1crb6RMdDC7R4XOBOptiaQ1FxVyRdV46QuMTEvvtf+UtxkvDNLrLvHB4RGf4nSt1O4z6KUSrpgZSeINnV7q1G7LOekKQeMTj6z/UqQKEUuwS1Jc9r0abH87rapCyzAgMq6EeOhHDQk7DSs1dqTaiz0/2Uy1P+SoFif46hyOlQVXgQNoVqKEZm36NRYNxvu6Gpw7coYFCt7NxzHaAM5LkQKXqRENrTZD1I/ncOsYp7t6ECDfnQph4pyWQ+/TC4vqEV8VWkCHU9M+XcBjEojO4j23Harg0m871iSKBrPQJfdhSCLCeqUwMcpLHTdR8Myo48yEarMDUzzCboEKMYvv1FgN9tm5Gea+2q3a1A4oZU36iSYMhdziCSLlzLhliPXTkfZzSYj8VdtEBlwPECWhc6gYYfUx/OBuyDFVxJhOQvtEGzBv+VI0QnjpvprEudm7QmZsFsBEu1azzxEa+KoAu6hZfg0gdUdWR4JSk7B9nPTMYnUHH1FuA6IZXIg8wlxcczbS5b0nTMaQ9mELHmLc7lCCpKcD1oQBh6M45IEYn/bbbO6vvliS3Dpq7/GFTWSmXwdZjRqb9lba5Mt0+hF4hK1+rmWANwddUifS57AMsCcW0CK3QGe53V6vwObY62+5g6DYI/yifRpHrqcSj64iiih7AY=
  file: TicTacToe-console-build-jar-with-dependencies
  skip_cleanup: true
  on:
    tags: false
  provider: heroku
  api_key:
    secure: CthNov0sPXGJGMLDna0oDCuYZaAaJ07VlFlgRJFejnYMfgV2hZiVVlX3wuxkOp3uifDmqB5GXIR63F3jHZfu7xCOdDNiA0+W0Ut8cwUsIoE7MUcCYz1/JbJdjYgs4BdVO4dNG3GaZpNSZXngVVZqpk5pB1ZceRs3sCrNoCUmy2tHr9gdDcE7MY7VOFdAU1ryPJITwO7A8uFXTmSyWC1i91duotegSdiaabmrys59gIFLCet+wLn1U+fHk3Dbj2n1kKdZgILQDxr8WDDi05oyOEAdUufakJim2+oZTNcC6+CZjbzVzSGvgZLKDLRaGUX3rMzGcjqdsrwF489HVGFHg/uYvHLm9Ba3I5LP0E+5D7Eya1WrV4zKfuTPi0xBEGwztQlBvsRK7Q21bcTe+gVEl0b+eSATwaYnvc8q9hxLFz6PuiPaKwe/fPHgpFluYU5GiWuL4aETA2/bVH9xUXVW6hmjG1tknBn/Wl6ZE9QiOa1rtaLPjhUE89QHJQr/hVFgjDsJMAoM5cbrwR0R23vyQ410Ivv+3ae/8vn6MYFAGcCUZOv5YqTb1a2YsJqZK5OOYsjmDqOJthlCrBypbFNfD8vawdKZZ9wcx9vBIcn0xzFMzqXTkX7UQJ/SdpV7yo99hZ6A7vX2+gTmha+wt9EQhUD+xbE95hovMaNENTCRg+g=
  app: jatj-tictactoe
