language: java
jdk:
- oraclejdk8
deploy:
  api_key:
    secure: CthNov0sPXGJGMLDna0oDCuYZaAaJ07VlFlgRJFejnYMfgV2hZiVVlX3wuxkOp3uifDmqB5GXIR63F3jHZfu7xCOdDNiA0+W0Ut8cwUsIoE7MUcCYz1/JbJdjYgs4BdVO4dNG3GaZpNSZXngVVZqpk5pB1ZceRs3sCrNoCUmy2tHr9gdDcE7MY7VOFdAU1ryPJITwO7A8uFXTmSyWC1i91duotegSdiaabmrys59gIFLCet+wLn1U+fHk3Dbj2n1kKdZgILQDxr8WDDi05oyOEAdUufakJim2+oZTNcC6+CZjbzVzSGvgZLKDLRaGUX3rMzGcjqdsrwF489HVGFHg/uYvHLm9Ba3I5LP0E+5D7Eya1WrV4zKfuTPi0xBEGwztQlBvsRK7Q21bcTe+gVEl0b+eSATwaYnvc8q9hxLFz6PuiPaKwe/fPHgpFluYU5GiWuL4aETA2/bVH9xUXVW6hmjG1tknBn/Wl6ZE9QiOa1rtaLPjhUE89QHJQr/hVFgjDsJMAoM5cbrwR0R23vyQ410Ivv+3ae/8vn6MYFAGcCUZOv5YqTb1a2YsJqZK5OOYsjmDqOJthlCrBypbFNfD8vawdKZZ9wcx9vBIcn0xzFMzqXTkX7UQJ/SdpV7yo99hZ6A7vX2+gTmha+wt9EQhUD+xbE95hovMaNENTCRg+g=
